package com.specialed.assistant.exception;

public enum ErrorCode {
    VALIDATION_ERROR(40001),
    CURRENT_STUDENT_REQUIRED(40002),
    WECHAT_CODE_INVALID(40010),
    WECHAT_BINDING_CODE_INVALID(40011),
    UNAUTHORIZED_TEACHER(40101),
    UNAUTHORIZED_SESSION(40102),
    WECHAT_BINDING_REQUIRED(40301),
    RESOURCE_NOT_FOUND(40401),
    RESOURCE_CONFLICT(40901),
    PROGRESS_CONFIRMATION_REQUIRED(40902),
    WECHAT_TEACHER_ALREADY_BOUND(40903),
    INTERNAL_ERROR(50000),
    WECHAT_SERVICE_UNAVAILABLE(50201),
    WECHAT_NOT_CONFIGURED(50301);

    private final int value;

    ErrorCode(int value) {
        this.value = value;
    }

    public int value() {
        return value;
    }
}
